### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rngtng** [rngtng/vizard#5]
Todos
- [ ] give logout option
- [x] show rendered by at the bottom
- [ ] option to switch presentation
- [ ] show login avatar
- [ ] nice fail when github error
- [x] rename to vizard
- [ ] <del>update bazooka</del>
- [ ] switch to reactjs

browser:
- [ ] make nav menu folder clickable
- [ ] style menu
- [x] images next to each other

editor:
- [ ] add save 
- [x] option for autosave
- [ ] dont ESC when fancybox
- [ ] right hover brings one back
- [ ] option to move back in time
- [ ] throttle on change (on error)
- [x] show welcome text
- [ ] option to save to new file
- [ ] gist integration
- [x] style github login
- [ ] enable scrolling for preview
- [ ] show fancybox on click
- [x] on escapego  to '/'
- [ ] switch to https://github.com/JedWatson/react-codemirror?
- [ ] Help screen. Keybindings/plant Syntax
- [ ] Better error message
- [ ] Gist Integration
- [x] Deploy github
- [ ] Move to nodejs
